[project]
name = "github_events_analysis"
version = "0.0.1"
authors = [
  { name="Vicente J. Rives Molina", email="vicente.rives.molina@gmail.com" },
]
description = "A small project to analyse GitHub events"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/vrivesmolina/github_events_analysis"